name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-fast:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webscraper

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run unit and fast application tests
        run: ./mvnw --no-transfer-progress test -DexcludedGroups=integration

  integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webscraper

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run integration tests
        run: ./mvnw --no-transfer-progress test -Dgroups=integration
